apiVersion: v1
kind: Service
metadata:
    name: "mirrorbot1-56dd"
    labels:
        app: "mirrorbot1-56dd"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "mirrorbot1-56dd"