apiVersion: v1
kind: Service
metadata:
    name: "anshumanmirrorbot-820d"
    labels:
        app: "anshumanmirrorbot-820d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "anshumanmirrorbot-820d"