on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: anshumanmirrorbot.azurecr.io
        username: ${{ secrets.acr_anshumanmirrorbot_username }}
        password: ${{ secrets.acr_anshumanmirrorbot_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t anshumanmirrorbot.azurecr.io/mirrorbot1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push anshumanmirrorbot.azurecr.io/mirrorbot1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mirrorbot1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mirrorbot1a662 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mirrorbot1a662`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mirrorbot1a662
        container-registry-url: anshumanmirrorbot.azurecr.io
        container-registry-username: ${{ secrets.acr_anshumanmirrorbot_username }}
        container-registry-password: ${{ secrets.acr_anshumanmirrorbot_password }}
        secret-name: mirrorbot1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mirrorbot1a662
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          anshumanmirrorbot.azurecr.io/mirrorbot1:${{ github.sha }}
        imagepullsecrets: |
          mirrorbot1dockerauth
